Fixed typo in get_install_parameters.py
A typo on line 63 "cache_pin_token[s]" will cause the script to crash with AttributeError: 'Namespace' object has no attribute 'cache_pin_tokens'. Did you mean: 'cache_pin_token'?